# Generated by Django 5.1.1 on 2024-10-03 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_message_is_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
